---
apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k9s-kub/demo:v2.0.0
    ports:
    - containerPort: 8080
      name: http
      
    # Liveness Probe
    livenessProbe:
      httpGet:
        path: /
        port: http
        
    # Readiness Probe
    readinessProbe:
      httpGet:
        path: /
        port: http
  - name: sidecar
    image: gcr.io/k8s-k9s-kub/sidecar:v2.0.0
    command: [ "sh", "-c", "echo Sidecar running!" ]
  volumes:
  - name: data
    hostPath:
      path: /var/lib/app
  volumeMounts:
  - name: data
    mountPath: /data
