---
apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k9s-kub/demo:v2.0.0
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: USERNAME
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: PASSWORD
  secrets:
  - name: app-secrets
    secret:
      secretName: app-secrets
