---
apiVersion: v1
kind: Pod
metadata:
  name: app-resource
  labels:
    app: demo
spec:
  containers:
  - name: app-resource
    image: gcr.io/k8s-k9s-kub/demo:v2.0.0
    ports:
    - name: http
      containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
