---
kind: Pod
apiVersion: v1
metadata:
  name: app
  labels:
    app: demo
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k9s-kub/demo:v2.0.0
      ports:
        - name: http
          containerPort: 8080
      readinessProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 15
        periodSeconds: 20
