---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k9s-kub/demo:v2.0.0
    ports:
      - name: http
        containerPort: 8080
    volumeMounts:
      - name: data
        mountPath: /data
    livenessProbe:
      httpGet:
        path: /
        port: http
    readinessProbe:
      httpGet:
        path: /
        port: http
  volumes:
    - name: data
      hostPath:
        path: /var/lib/app
