---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  template:
    spec:
      containers:
      - name: app
        image: gcr.io/k8s-k9s-kub/demo:v2.0.0
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: /var/lib/app
      restartPolicy: OnFailure
