---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
spec:
  containers:
  - name: app
    image: gcr.io/k8s-k9s-kub/demo:v2.0.0
    ports:
      - containerPort: 8080
        name: http
